[[slm-stop]]
=== Stop Snapshot Lifecycle Management API

[subs="attributes"]
++++
<titleabbrev>Stop Snapshot Lifecycle Management</titleabbrev>
++++

Stop the Snapshot Lifecycle Management (SLM) plugin.

[[slm-stop-request]]
==== {api-request-title}

`POST /_ilm/stop`

[[slm-stop-desc]]
==== {api-description-title}

Halts all snapshot lifecycle management operations and stops the SLM plugin.
This is useful when you are performing maintenance on the cluster and need to
prevent SLM from performing any actions on your indices. Note that this API does
not stop any snapshots that are currently in progress, and that snapshots can
still be taken manually via the <<slm-api-execute,Execute Policy API>> even
when SLM is stopped.

The API returns as soon as the stop request has been acknowledged, but the
plugin might continue to run until in-progress operations complete and the plugin
can be safely stopped. Use the  <<slm-get-status, Get SLM Status>> API to see
if SLM is running. 

==== Request Parameters

include::{docdir}/rest-api/common-parms.asciidoc[tag=timeoutparms]

==== Authorization

You must have the `manage_slm` cluster privilege to use this API.
For more information, see <<security-privileges>>.

[[slm-stop-example]]
==== {api-examples-title}

Stops the SLM plugin.

[source,console]
--------------------------------------------------
POST _slm/stop
--------------------------------------------------
// TEST[continued]

If the request does not encounter errors, you receive the following result:

[source,console-result]
--------------------------------------------------
{
  "acknowledged": true
}
--------------------------------------------------