[[slm-api-get-status]]
=== Get snapshot lifecycle management status API

[subs="attributes"]
++++
<titleabbrev>Get snapshot lifecycle management status</titleabbrev>
++++

Retrieves the status of snapshot lifecycle management (SLM).

[[slm-api-get-status-request]]
==== {api-request-title}

`GET /_slm/status`

[[slm-api-get-status-desc]]
==== {api-description-title}

Returns the status of the SLM plugin. 
The `operation_mode` field in the response shows one of three states: 
`STARTED`, `STOPPING`, or `STOPPED`. 
You halt and restart the SLM plugin with the
<<slm-api-stop, stop>> and <<slm-api-start, start>>  APIs.

==== Request Parameters

include::{docdir}/rest-api/common-parms.asciidoc[tag=timeoutparms]

[[slm-api-get-status-prereqs]]
==== {api-prereq-title}

* If the {es} {security-features} are enabled, you must have the 
`manage_slm` or `read_slm` cluster privileges to use this API. 
For more information, see <<security-privileges>>.

[[slm-api-get-status-example]]
==== {api-examples-title}

Get the SLM plugin status:

[source,console]
--------------------------------------------------
GET _slm/status
--------------------------------------------------

If the request succeeds, the body of the response shows the operation mode:

[source,console-result]
--------------------------------------------------
{
  "operation_mode": "RUNNING"
}
--------------------------------------------------
// TESTRESPONSE[s/"operation_mode": "RUNNING"/"operation_mode": $body.operation_mode/]
